
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean install package --file pom.xml
      - name: Export JAR file
        run: export JAR_FILE=$(ls target/*.jar)
      - name: pwd
        run: sudo pwd .
      - name: remove files
        run: sudo rm -rf /opt/pipx/venvs/ansible-core/lib/python3.10/site-packages/ansible_collections/cyberark/conjur/roles/conjur_host_identity/tests/.dockerignore /usr/local/lib/heroku/node_modules/@heroku-cli/plugin-redis-v5/node_modules/cpu-features/deps/cpu_features/.dockerignore /home/runneradmin/.nvm/.dockerignore /home/linuxbrew/.linuxbrew/Homebrew/.dockerignore /home/runner/.nvm/.dockerignore /home/runner/work/_actions/docker/login-action/f4ef78c080cd8ba55a85445d5b36e214a81df20a/.dockerignore /home/runner/work/_actions/docker/metadata-action/9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7/.dockerignore /etc/skel/.nvm/.dockerignore
      - name: Create staging directory
        run: sudo mkdir -p /home/staging/
      - name: Copying Artifact to another directory
        run: sudo cp target/*.jar /home/staging/
      - name: Move Jar files to build context
        run: mv /home/staging/*.jar ./
      - name: Persist Artifact
        uses: actions/upload-artifact@v2
        with:
          name: maven-artifacts
          path: target
      - name: Print package location
        run: |
          echo "Maven package file is located at: $(find . -type f -name '*.jar')"
          
          
      - name: Build with Maven
        run: mvn -B -X clean install package --file pom.xml
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: http://3.87.214.2:8081/
          username: admin
          password: ${{ secrets.password }}
          format: maven2
          repository: mini-project
          coordinates: groupId=com.example artifactId=app version=1.0.0
          assets: extension=jar
          filename: ./target/MiniProject-1.0-SNAPSHOT.jar
          
          
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: docker build -f ./Dockerfile.yml -t docker.io/surusuraj200021/mini-project:latest .
    
      - name: Push Docker image to Docker Hub
        run: docker push docker.io/surusuraj200021/mini-project:latest
 
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: sqp_a9726d65af895f050e9816642da97f18d4c958c5   
          SONAR_HOST_URL: http://44.204.163.8:9000/  
        with:
          args:
            -Dsonar.projectKey=MiniProject
